# Generated by Django 3.1.2 on 2020-11-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Имя просящего.')),
                ('email', models.EmailField(max_length=254, verbose_name='Email просящего.')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон.')),
                ('message', models.TextField(verbose_name='Сообщение.')),
                ('is_worked', models.BooleanField(default=False, verbose_name='Если обработано.')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь.',
                'db_table': 'feedback',
            },
        ),
    ]
