# Generated by Django 3.1.3 on 2020-11-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item_page',
            table='Каталог товаров',
        ),
    ]
